CREATE DATABASE IF NOT EXISTS ai_camera_pos CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ai_camera_pos;

CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,username VARCHAR(50) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,role ENUM('admin','cashier') NOT NULL DEFAULT 'cashier',status ENUM('active','inactive') NOT NULL DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE categories (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL UNIQUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE products (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL,sku VARCHAR(60) NOT NULL UNIQUE,category_id INT UNSIGNED NULL,price DECIMAL(10,2) NOT NULL DEFAULT 0,stock_quantity INT NOT NULL DEFAULT 0,image VARCHAR(255) NULL,status ENUM('active','inactive') NOT NULL DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT fk_product_category FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE SET NULL,INDEX idx_product_name(name)) ENGINE=InnoDB;
CREATE TABLE orders (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,receipt_number VARCHAR(40) NOT NULL UNIQUE,cashier_id INT UNSIGNED NOT NULL,subtotal DECIMAL(10,2) NOT NULL,discount DECIMAL(10,2) NOT NULL DEFAULT 0,grand_total DECIMAL(10,2) NOT NULL,payment_method ENUM('cash','tng') NOT NULL,amount_paid DECIMAL(10,2) NOT NULL,change_amount DECIMAL(10,2) NOT NULL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_order_cashier FOREIGN KEY(cashier_id) REFERENCES users(id),INDEX idx_order_date(created_at)) ENGINE=InnoDB;
CREATE TABLE order_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NOT NULL,product_id INT UNSIGNED NOT NULL,product_name VARCHAR(150) NOT NULL,sku VARCHAR(60) NOT NULL,price DECIMAL(10,2) NOT NULL,quantity INT NOT NULL,total DECIMAL(10,2) NOT NULL,CONSTRAINT fk_item_order FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,CONSTRAINT fk_item_product FOREIGN KEY(product_id) REFERENCES products(id)) ENGINE=InnoDB;
CREATE TABLE settings (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,setting_key VARCHAR(100) NOT NULL UNIQUE,setting_value TEXT NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NULL,action VARCHAR(100) NOT NULL,details TEXT NULL,ip_address VARCHAR(45) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_audit_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;

INSERT INTO users(name,username,password,role) VALUES ('System Admin','admin','$2y$12$grcelcLQZDgOV2DhRQumle9a3LDeaRSV785jbmzu0nLp7Zq2J449W','admin');
INSERT INTO categories(name) VALUES ('Drinks'),('Food'),('Household');
INSERT INTO products(name,sku,category_id,price,stock_quantity) VALUES ('Coca Cola 500ml','CC500',1,2.50,50),('White Bread','BR001',2,3.00,30),('Mineral Water 500ml','MW500',1,1.20,100);
INSERT INTO settings(setting_key,setting_value) VALUES ('shop_name','My AI Shop'),('gemini_api_url','https://generativelanguage.googleapis.com/v1/models/{model}:generateContent'),('gemini_api_key',''),('gemini_model','gemini-3.7-flash'),('gemini_api_key_1',''),('gemini_model_1','gemini-3.7-flash'),('gemini_active_slot','1'),('low_stock_threshold','5');
