<?php
require __DIR__.'/../includes/bootstrap.php';require_login('admin');
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=$_POST['action']??'';
 if($action==='delete'){$id=(int)$_POST['id'];try{$s=db()->prepare('DELETE FROM products WHERE id=?');$s->execute([$id]);audit('delete_product',(string)$id);flash('success','Product deleted.');}catch(PDOException){flash('danger','Product has sales records and cannot be deleted. Set it inactive instead.');}redirect('admin/products.php');}
 $id=(int)($_POST['id']??0);$name=trim($_POST['name']??'');$sku=trim($_POST['sku']??'');$category=(int)($_POST['category_id']??0)?:null;$price=(float)($_POST['price']??0);$stock=(int)($_POST['stock_quantity']??0);$status=in_array($_POST['status']??'', ['active','inactive'],true)?$_POST['status']:'active';
 if($name===''||$sku===''||$price<0||$stock<0){flash('danger','Please enter valid product details.');redirect('admin/products.php'.($id?'?edit='.$id:''));}
 $image=null;if(!empty($_FILES['image']['name'])){$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];$mime=(new finfo(FILEINFO_MIME_TYPE))->file($_FILES['image']['tmp_name']);if(!isset($allowed[$mime])||$_FILES['image']['size']>5*1024*1024){flash('danger','Image must be JPG, PNG or WebP under 5 MB.');redirect('admin/products.php');}$image=bin2hex(random_bytes(12)).'.'.$allowed[$mime];move_uploaded_file($_FILES['image']['tmp_name'],__DIR__.'/../uploads/products/'.$image);}
 try{if($id){$sql='UPDATE products SET name=?,sku=?,category_id=?,price=?,stock_quantity=?,status=?'.($image?',image=?':'').' WHERE id=?';$args=[$name,$sku,$category,$price,$stock,$status];if($image)$args[]=$image;$args[]=$id;db()->prepare($sql)->execute($args);audit('update_product',(string)$id);}else{db()->prepare('INSERT INTO products(name,sku,category_id,price,stock_quantity,image,status) VALUES(?,?,?,?,?,?,?)')->execute([$name,$sku,$category,$price,$stock,$image,$status]);audit('create_product',$sku);}flash('success','Product saved.');}catch(PDOException){flash('danger','Could not save. The SKU may already exist.');}redirect('admin/products.php');
}
$edit=null;if(isset($_GET['edit'])){$s=db()->prepare('SELECT * FROM products WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();}
$categories=db()->query('SELECT * FROM categories ORDER BY name')->fetchAll();$products=db()->query('SELECT p.*,c.name category FROM products p LEFT JOIN categories c ON c.id=p.category_id ORDER BY p.id DESC')->fetchAll();$pageTitle='Products';require __DIR__.'/../includes/header.php';?>
<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 mb-0">Products</h1><button class="btn btn-primary" data-bs-toggle="collapse" data-bs-target="#productForm">+ Add Product</button></div>
<div id="productForm" class="collapse <?= $edit?'show':'' ?>"><div class="card p-3 mb-4"><h2 class="h5"><?= $edit?'Edit':'Add' ?> Product</h2><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=e($edit['id']??'')?>"><div class="row g-3"><div class="col-md-4"><label class="form-label">Name</label><input class="form-control" name="name" value="<?=e($edit['name']??'')?>" required></div><div class="col-md-2"><label class="form-label">SKU</label><input class="form-control" name="sku" value="<?=e($edit['sku']??'')?>" required></div><div class="col-md-2"><label class="form-label">Category</label><select class="form-select" name="category_id"><option value="">None</option><?php foreach($categories as $c):?><option value="<?=$c['id']?>" <?=($edit['category_id']??'')==$c['id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select></div><div class="col-md-2"><label class="form-label">Price (RM)</label><input class="form-control" type="number" min="0" step="0.01" name="price" value="<?=e($edit['price']??'0')?>" required></div><div class="col-md-2"><label class="form-label">Stock</label><input class="form-control" type="number" min="0" name="stock_quantity" value="<?=e($edit['stock_quantity']??'0')?>" required></div><div class="col-md-4"><label class="form-label">Image</label><input class="form-control" type="file" name="image" accept="image/jpeg,image/png,image/webp"></div><div class="col-md-2"><label class="form-label">Status</label><select class="form-select" name="status"><option value="active">Active</option><option value="inactive" <?=($edit['status']??'')==='inactive'?'selected':''?>>Inactive</option></select></div><div class="col-12"><button class="btn btn-primary">Save Product</button> <a class="btn btn-light" href="products.php">Cancel</a></div></div></form></div></div>
<div class="card p-3"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Image</th><th>Name / SKU</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($products as $p):?><tr><td><?php if($p['image']):?><img class="product-thumb" src="<?=e(url('uploads/products/'.$p['image']))?>"><?php else:?><div class="product-thumb d-grid place-items-center"></div><?php endif;?></td><td><strong><?=e($p['name'])?></strong><br><small><?=e($p['sku'])?></small></td><td><?=e($p['category']??'-')?></td><td><?=money($p['price'])?></td><td><?=e($p['stock_quantity'])?></td><td><?=e($p['status'])?></td><td class="text-nowrap"><a class="btn btn-sm btn-outline-primary" href="?edit=<?=$p['id']?>">Edit</a> <form class="d-inline" method="post" onsubmit="return confirm('Delete this product?')"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$p['id']?>"><button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr><?php endforeach;?></tbody></table></div></div>
<?php require __DIR__.'/../includes/footer.php';
