<?php
require __DIR__.'/../includes/bootstrap.php';require_login('admin');
$suggestedModels=['gemini-3.7-flash','gemini-3.5-flash-lite','gemini-3.1-flash-lite'];
function save_setting_value(string $key,string $value):void{$s=db()->prepare('INSERT INTO settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)');$s->execute([$key,$value]);}
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();
 $apiUrl=trim($_POST['gemini_api_url']??'https://generativelanguage.googleapis.com/v1/models/{model}:generateContent');
 $apiUrl=preg_replace('#/models/[^/{:]+:generateContent#','/models/{model}:generateContent',$apiUrl);
 $apiParts=parse_url($apiUrl);
 if(($apiParts['scheme']??'')!=='https'||strtolower($apiParts['host']??'')!=='generativelanguage.googleapis.com'||!str_contains($apiUrl,'{model}')){flash('danger','AI API URL must use the official Google Gemini HTTPS endpoint and include {model}.');redirect('admin/settings.php');}
 save_setting_value('gemini_api_url',$apiUrl);save_setting_value('shop_name',trim($_POST['shop_name']??'My AI Shop'));save_setting_value('low_stock_threshold',(string)max(0,(int)($_POST['low_stock_threshold']??5)));save_setting_value('gemini_active_slot',(string)max(1,min(5,(int)($_POST['gemini_active_slot']??1))));
 $newKey=trim($_POST['gemini_api_key']??'');$clearKey=isset($_POST['clear_gemini_api_key']);
 if($newKey!==''||$clearKey){save_setting_value('gemini_api_key',$clearKey?'':$newKey);save_setting_value('gemini_api_key_1',$clearKey?'':$newKey);}
 for($slot=1;$slot<=5;$slot++){
  $model=strtolower(trim($_POST['gemini_model_'.$slot]??''));$model=preg_replace('/\s+/','-',$model);save_setting_value('gemini_model_'.$slot,$model);
  if($slot===1)save_setting_value('gemini_model',$model);
 }
 audit('update_settings','Updated Gemini fallback slots');flash('success','Settings saved. Gemini will try configured slots from 1 to 5.');redirect('admin/settings.php');
}
$pageTitle='Settings';require __DIR__.'/../includes/header.php';?>
<h1 class="h3 mb-3">System Settings</h1><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><div class="card p-4 mb-4" style="max-width:900px"><label class="form-label">Shop Name</label><input class="form-control mb-3" name="shop_name" value="<?=e(setting('shop_name','My AI Shop'))?>" required><label class="form-label">Low-stock Threshold</label><input class="form-control" style="max-width:220px" type="number" min="0" name="low_stock_threshold" value="<?=e(setting('low_stock_threshold','5'))?>"></div>
<div class="card p-4" style="max-width:900px"><h2 class="h5">Gemini Model Fallback</h2><p class="text-muted">Enter one API key only. Choose which model to use now. If Google returns a quota or rate limit, the system automatically tries the following models.</p><?php $hasSharedKey=setting('gemini_api_key',setting('gemini_api_key_1'))!=='';$activeSlot=(int)setting('gemini_active_slot','1');?><div class="border rounded p-3 mb-3"><label class="form-label fw-bold">AI API URL</label><input class="form-control" type="text" name="gemini_api_url" value="<?=e(setting('gemini_api_url','https://generativelanguage.googleapis.com/v1/models/{model}:generateContent'))?>" required><div class="form-text">Use <code>{model}</code> where the selected model ID belongs. A pasted fixed Gemini model URL is converted automatically.</div></div><div class="border rounded p-3 mb-4"><div class="d-flex justify-content-between mb-2"><strong>Shared Gemini API Key</strong><span class="badge <?=$hasSharedKey?'bg-success':'bg-secondary'?>"><?=$hasSharedKey?'API key saved':'No API key'?></span></div><input class="form-control" type="password" name="gemini_api_key" placeholder="<?=$hasSharedKey?'Leave blank to keep saved key':'Enter API key once'?>" autocomplete="new-password"><?php if($hasSharedKey):?><label class="form-check mt-2"><input class="form-check-input" type="checkbox" name="clear_gemini_api_key"> Remove saved key</label><?php endif;?></div><div class="border border-primary rounded p-3 mb-4"><label class="form-label fw-bold">Current Active Model</label><select class="form-select form-select-lg" name="gemini_active_slot"><?php for($choice=1;$choice<=5;$choice++):$choiceLegacy=$choice===1?setting('gemini_model','gemini-3.7-flash'):'';$choiceModel=setting('gemini_model_'.$choice,$choiceLegacy);?><option value="<?=$choice?>" <?=$activeSlot===$choice?'selected':''?>>Model <?=$choice?><?= $choiceModel!==''?' — '.e($choiceModel):' — Not configured' ?></option><?php endfor;?></select><div class="form-text">This model is tried first. Fallback continues with the next model number.</div></div><datalist id="geminiModels"><?php foreach($suggestedModels as $m):?><option value="<?=e($m)?>"><?php endforeach;?></datalist>
<?php for($slot=1;$slot<=5;$slot++):$legacyModel=$slot===1?setting('gemini_model','gemini-3.7-flash'):'';$model=setting('gemini_model_'.$slot,$legacyModel);?><div class="border rounded p-3 mb-3"><strong>Priority Model <?=$slot?></strong><label class="form-label mt-2">Model ID</label><input class="form-control" name="gemini_model_<?=$slot?>" list="geminiModels" value="<?=e($model)?>" placeholder="Example: gemini-3.7-flash"></div><?php endfor;?>
<button class="btn btn-primary btn-lg">Save Settings</button> <button class="btn btn-outline-success btn-lg" type="button" id="testAi">Test AI Fallback</button><div id="testResult" class="mt-3"></div></div></form>
<script>document.getElementById('testAi').onclick=async()=>{const el=document.getElementById('testResult'),form=document.querySelector('form');el.className='mt-3 alert alert-info';el.textContent='Saving your current model selection...';try{await fetch(location.href,{method:'POST',body:new FormData(form)});el.textContent='Testing the saved active model...';const r=await fetch('<?=e(url('api/test-ai.php'))?>',{method:'POST',headers:{'X-CSRF-Token':'<?=e(csrf_token())?>'}});const d=await r.json();el.textContent=d.message;el.className='mt-3 alert '+(d.success?'alert-success':'alert-danger')}catch(e){el.textContent='Connection test failed.';el.className='mt-3 alert alert-danger'}}</script>
<?php require __DIR__.'/../includes/footer.php';
