<?php
require __DIR__.'/../includes/bootstrap.php';require_login('admin');
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'save';$id=(int)($_POST['id']??0);if($action==='delete'){if($id===user()['id']){flash('danger','You cannot delete your own account.');}else{try{db()->prepare('DELETE FROM users WHERE id=?')->execute([$id]);flash('success','User deleted.');}catch(PDOException){flash('danger','User has sales records. Set the user inactive instead.');}}redirect('admin/users.php');}
 $name=trim($_POST['name']??'');$username=trim($_POST['username']??'');$role=in_array($_POST['role']??'', ['admin','cashier'],true)?$_POST['role']:'cashier';$status=($_POST['status']??'')==='inactive'?'inactive':'active';$password=$_POST['password']??'';
 try{if($id){$sql='UPDATE users SET name=?,username=?,role=?,status=?'.($password!==''?',password=?':'').' WHERE id=?';$args=[$name,$username,$role,$status];if($password!=='')$args[]=password_hash($password,PASSWORD_DEFAULT);$args[]=$id;db()->prepare($sql)->execute($args);}else{if(strlen($password)<8)throw new RuntimeException('Password must contain at least 8 characters.');db()->prepare('INSERT INTO users(name,username,password,role,status) VALUES(?,?,?,?,?)')->execute([$name,$username,password_hash($password,PASSWORD_DEFAULT),$role,$status]);}flash('success','User saved.');}catch(Throwable $e){flash('danger',$e instanceof RuntimeException?$e->getMessage():'Username already exists.');}redirect('admin/users.php');}
$edit=null;if(isset($_GET['edit'])){$s=db()->prepare('SELECT id,name,username,role,status FROM users WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();}$users=db()->query('SELECT id,name,username,role,status,created_at FROM users ORDER BY id DESC')->fetchAll();$pageTitle='Users';require __DIR__.'/../includes/header.php';?>
<h1 class="h3">User Management</h1><div class="card p-3 mb-4"><h2 class="h5"><?= $edit?'Edit':'Add' ?> User</h2><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=e($edit['id']??'')?>"><div class="row g-3"><div class="col-md-3"><input class="form-control" name="name" placeholder="Full name" value="<?=e($edit['name']??'')?>" required></div><div class="col-md-3"><input class="form-control" name="username" placeholder="Username" value="<?=e($edit['username']??'')?>" required></div><div class="col-md-2"><input class="form-control" type="password" name="password" placeholder="<?= $edit?'New password (optional)':'Password (8+ chars)' ?>" <?= $edit?'':'required' ?>></div><div class="col-md-2"><select class="form-select" name="role"><option value="cashier">Cashier</option><option value="admin" <?=($edit['role']??'')==='admin'?'selected':''?>>Admin</option></select></div><div class="col-md-2"><select class="form-select" name="status"><option value="active">Active</option><option value="inactive" <?=($edit['status']??'')==='inactive'?'selected':''?>>Inactive</option></select></div><div class="col-12"><button class="btn btn-primary">Save User</button></div></div></form></div>
<div class="card p-3 table-responsive"><table class="table"><thead><tr><th>Name</th><th>Username</th><th>Role</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody><?php foreach($users as $u):?><tr><td><?=e($u['name'])?></td><td><?=e($u['username'])?></td><td><?=e($u['role'])?></td><td><?=e($u['status'])?></td><td><?=e($u['created_at'])?></td><td><a class="btn btn-sm btn-outline-primary" href="?edit=<?=$u['id']?>">Edit</a> <form method="post" class="d-inline" onsubmit="return confirm('Delete this user?')"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$u['id']?>"><button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr><?php endforeach;?></tbody></table></div>
<?php require __DIR__.'/../includes/footer.php';
