<?php $pageTitle = $pageTitle ?? 'AI Camera POS'; $flash = take_flash(); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?= e($pageTitle) ?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="<?= e(url('assets/css/app.css?v='.filemtime(__DIR__.'/../assets/css/app.css'))) ?>" rel="stylesheet"></head>
<body><nav class="navbar navbar-expand-lg navbar-dark"><div class="container-fluid"><a class="navbar-brand fw-bold" href="<?= e(url(user() && user()['role']==='admin' ? 'admin/dashboard.php' : 'cashier/pos.php')) ?>"><span class="brand-mark">AI</span><span>Camera POS</span></a>
<?php if(user()): ?><div class="d-flex align-items-center gap-2 text-white"><span class="small user-chip"><strong><?= e(user()['name']) ?></strong> <span class="user-role opacity-75">· <?= e(ucfirst(user()['role'])) ?></span></span><a class="btn btn-sm btn-outline-light" href="<?= e(url('logout.php')) ?>">Logout</a></div><?php endif; ?></div></nav>
<?php if(user()): ?><div class="app-nav border-bottom"><div class="container-fluid nav-scroll py-2 d-flex gap-2">
<?php if(user()['role']==='admin'): ?><a class="btn btn-sm btn-outline-primary" href="<?= e(url('admin/dashboard.php')) ?>">Dashboard</a><a class="btn btn-sm btn-outline-primary" href="<?= e(url('admin/products.php')) ?>">Products</a><a class="btn btn-sm btn-outline-primary" href="<?= e(url('admin/users.php')) ?>">Users</a><a class="btn btn-sm btn-outline-primary" href="<?= e(url('admin/sales.php')) ?>">Sales</a><a class="btn btn-sm btn-outline-primary" href="<?= e(url('admin/settings.php')) ?>">Settings</a><?php endif; ?>
<a class="btn btn-sm btn-pos" href="<?= e(url('cashier/pos.php')) ?>">● Open POS</a><a class="btn btn-sm btn-outline-secondary" href="<?= e(url('cashier/history.php')) ?>"><?=user()['role']==='admin'?'All Sales':'My Sales'?></a></div></div><?php endif; ?>
<main class="container-fluid py-4"><?php if($flash): ?><div class="alert alert-<?= e($flash[0]) ?> alert-dismissible fade show"><?= e($flash[1]) ?><button class="btn-close" data-bs-dismiss="alert"></button></div><?php endif; ?>
