<?php
require __DIR__.'/../includes/bootstrap.php';
set_exception_handler(static function(Throwable $e):void{error_log('AI detect error: '.$e->getMessage());if(!headers_sent())header('Content-Type: application/json');echo json_encode(['success'=>false,'message'=>'The AI service could not complete the request. Check Test AI Fallback in Settings.','error_type'=>'server_error']);});
require_login();verify_csrf();header('Content-Type: application/json');
if(empty($_FILES['image']['tmp_name'])){http_response_code(422);echo json_encode(['success'=>false,'message'=>'Please capture or choose an image.']);exit;}
$allowed=['image/jpeg','image/png','image/webp'];$mime=(new finfo(FILEINFO_MIME_TYPE))->file($_FILES['image']['tmp_name']);if(!in_array($mime,$allowed,true)||$_FILES['image']['size']>8*1024*1024){http_response_code(422);echo json_encode(['success'=>false,'message'=>'Use a JPG, PNG or WebP image under 8 MB.']);exit;}
$catalog=db()->query("SELECT name,sku FROM products WHERE status='active'")->fetchAll();$catalogText=implode("\n",array_map(fn($p)=>$p['name'].' | SKU '.$p['sku'],$catalog));$prompt="Identify shop products and count visible units. Only select from this catalog:\n$catalogText\nReturn only valid JSON, no markdown: {\"items\":[{\"sku\":\"catalog SKU\",\"quantity\":1}],\"unknown\":[\"short description\"]}. Never invent a SKU. If uncertain, put it in unknown.";
$payload=['contents'=>[['parts'=>[['text'=>$prompt],['inline_data'=>['mime_type'=>$mime,'data'=>base64_encode(file_get_contents($_FILES['image']['tmp_name']))]]]]],'generationConfig'=>['responseMimeType'=>'application/json','temperature'=>0.1]];
$result=gemini_generate($payload,45);if(!$result['success']){echo json_encode(['success'=>false,'message'=>$result['message'],'error_type'=>'gemini_request_failed']);exit;}
$response=$result['body'];$text=$response['candidates'][0]['content']['parts'][0]['text']??'';$detected=json_decode($text,true);if(!is_array($detected)){echo json_encode(['success'=>false,'message'=>'AI returned an unreadable response. Try a clearer photo.','error_type'=>'invalid_ai_response']);exit;}
$matched=[];foreach(($detected['items']??[]) as $item){$sku=trim((string)($item['sku']??''));$qty=max(1,min(99,(int)($item['quantity']??1)));$s=db()->prepare("SELECT id,name,sku,price,stock_quantity,image FROM products WHERE sku=? AND status='active' LIMIT 1");$s->execute([$sku]);if($p=$s->fetch()){$p['quantity']=min($qty,(int)$p['stock_quantity']);$matched[]=$p;}else{$detected['unknown'][]=$sku;}}
audit('ai_detect','Model slot '.$result['slot'].'; matched '.count($matched).' products');echo json_encode(['success'=>true,'products'=>$matched,'unknown'=>array_values(array_unique($detected['unknown']??[])),'model'=>$result['model'],'model_slot'=>$result['slot'],'fallback_count'=>count($result['attempts'])],JSON_UNESCAPED_UNICODE);
